name: Build log-cleaner

on:
  push:
    # branches: [ "master" ]
  pull_request:
    # branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    # runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pyinstaller
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Create Executable
        run: |
          pyinstaller log-cleaner.spec
      - name: Archive Output
        uses: actions/upload-artifact@v4
        with:
          name: log-cleaner
          path: dist/log-cleaner.exe
